### ISSUE TITLE
chore: polish github actions workflow

### ISSUE THREAD

**Issue by ronething** [InterviewTips/algorithm-coding#62]
- cancel run workflow when PR submit a new commit.

```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: read-all
```
